### ISSUE TITLE
Libre Calc: Spreadsheet Grid Lines Color

### ISSUE THREAD

**Issue by GiggleSquid** [NeonGamerBot-QK/catppuccin-libre-office#1]
Love the theme!

Just wanted to check:
The spreadsheet grid lines are set to the background color, is this intentional design, or an oversight?

~~Setting boarders for cells is colored as expected~~
Boarders for cells should probably be something like surface2 or overlay0

**Comment by GiggleSquid** [comment]
After a play around I think surface0 works for gridlines

**Comment by NeonGamerBot-QK** [comment]
> Love the theme!
> 
> Just wanted to check: The spreadsheet grid lines are set to the background color, is this intentional design, or an oversight?
> 
> ~Setting boarders for cells is colored as expected~ Boarders for cells should probably be something like surface2 or overlay0

Thank you for the feedback! ill make sure to checkout the spreadsheet section and to make sure its all correct
ill check & respond to this in around ~7 hours from now!

**Comment by NeonGamerBot-QK** [comment]
![image](https://github.com/user-attachments/assets/1bd11f76-62dc-438f-a8e9-22dc301b3ea6)
i see what you mean now! ill fix this tmrw or sometime in the near time future.

**Comment by GiggleSquid** [comment]
No worries, easy enough to change myself in the meantime!

**Comment by NeonGamerBot-QK** [comment]
ok, if you want to you can open up a PR!

**Comment by GiggleSquid** [comment]
Oh, I just meant in the gui for libeoffice. I don't even know what the format is for the theme config file

**Comment by NeonGamerBot-QK** [comment]
> Oh, I just meant in the gui for libeoffice. I don't even know what the format is for the theme config file

Ah mb. Which setting did you change to change spreadline colors?

**Comment by GiggleSquid** [comment]
![Screenshot_20240906_135349](https://github.com/user-attachments/assets/7916da1a-5f31-4898-b62c-5ad8572f2686)

That's just for the normal gridlines.

I haven't figured out which one sets boarder colors yet though
